# Generated by Django 4.2.5 on 2023-12-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_description', models.TextField(max_length=800)),
                ('video_link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(max_length=800),
        ),
    ]
